version: '3.9'

services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydb
    volumes:
      - ./mysql-data:/var/lib/mysql

  ubuntu:
    image: ubuntu
    tty: true
    stdin_open: true

volumes:
  mysql-data:
